### ISSUE TITLE
Promise Rejection in fallback

### ISSUE THREAD

**Issue by yharish991** [bucharest-gold/opossum#100]
Can i do something like this ?

```
function getCache(req, res) {
  return getCacheCB.fire(req.params.userId, req.headers.referer)
    .then(resObj => res.status(resObj.statusCode).send(
        userProfileSerializer(resObj.message, '1.0.0')))
    .catch(resObj => res.status(resObj.statusCode).send(errorSerializer(resObj, '1.0.0')));
}

getCacheCB.fallback((userId, referer) => {
  log.info('Get cache fallback'); // eslint-disable-line
  return service.fetchUserProfile(userId, referer)
});
``` 
Looks like Promise.reject does not seems to work.
I get this warning in the console  when the `service.fetchUserProfile(userId, referer)` function returns promise rejection
```
(node:78791) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 504 - "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>openresty/1.9.7.3</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by lance** [comment]
@yharish991 can you provide a reproducible test case? We are currently testing for fallback functions returning a rejected promise [here](https://github.com/bucharest-gold/opossum/blob/master/test/test.js#L574) without issue.

**Comment by lance** [comment]
@yharish991 you need to `.catch()` that rejected promise during the `fallback` event, is done [here](https://github.com/bucharest-gold/opossum/blob/master/test/test.js#L584-L588). The warning is not fatal, but will always occur unless the fallback's rejected promise is handled during the `fallback` event.

**Comment by lance** [comment]
@yharish991 I have applied a fix that allows you to handle the promise rejection on fallback directly from `breaker.fire()` instead of only within the `fallback` event. This will land in the next release, which should be available soon.
