### ISSUE TITLE
Get HystrixStats

### ISSUE THREAD

**Issue by DavideCarvalho** [bucharest-gold/opossum#124]
Is there any way of getting HystrixStats to open the stream url without opening a circuit?
I Tried the folowing code but it give's me an error "TypeError: Cannot read property 'name' of undefined"

```javascript
const circuitBreaker = require('opossum');
const circuit = circuitBreaker().circuit;
const hystrixStats = circuit.hystrixStats;
module.exports = (app) => {
  Verification = async (req, res, next) => {
    res.writeHead(200, {'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache', 'Connection': 'keep-alive'});
    res.write('retry: 10000\n');
    res.write('event: connecttime\n');
  
    hystrixStats.getHystrixStream().pipe(res);
  }
}
```

**Comment by lance** [comment]
@DavideCarvalho I don't understand why you would do this. The circuit in this case is never firing, so there is no data to pipe through the stream. That said, I don't think it should throw a `TypeError` in this case.

**Comment by DavideCarvalho** [comment]
In your example, you get the stream from only one circuit (at least i think it's from only one circuit, since you get the hystrixStatus from the circuit you just created), i'd like to know how aggregate all the stream so I can use on my url.

**Comment by lance** [comment]
I will take a look, but I do not believe this is currently possible. Please feel free to submit a feature request for this, and I will look into it.

**Comment by lance** [comment]
@davidecarvalho there is an open pull request for this here https://github.com/bucharest-gold/opossum/pull/140. If you have feedback on this it would be welcome.

**Comment by lance** [comment]
@DavideCarvalho can you confirm whether #140 addresses your concerns?

**Comment by lance** [comment]
I'm going to go ahead and close this. If you find that your issue has not been resolved, feel free to reopen or to create a new issue.
