### ISSUE TITLE
Consider moving linting to xo 

### ISSUE THREAD

**Issue by lance** [bucharest-gold/opossum#175]
eslint has become difficult to maintain and is the bulk of our greenkeeper work.

**Comment by danbev** [comment]
Is the only motivation to doing this that greenkeeper is a pain to maintain? Is there a reason that we update dev dependencies (and not just project/product dependencies) with greenkeeper?

**Comment by helio-frota** [comment]
I can add 2 more motivations: 

1. xo is catching a bit more suggestions for good code than raw-eslint (yup xo uses eslint under the covers)

2. less configuration for the project
