### ISSUE TITLE
halfOpen documentation is unclear regarding retry action

### ISSUE THREAD

**Issue by bartcone** [bucharest-gold/opossum#212]
The documentation makes it seem like the action that tripped the circuit should be re-executed when the circuit enters the `halfOpen` state (Fowler's post seemed to indicate the same thing). I'm not seeing this, rather it waits on the first successful request and then closes.

https://github.com/bucharest-gold/opossum#fallback

Bart

**Comment by lance** [comment]
You're right that the documentation is unclear in this regard. The current behavior is what is expected. In the `halfOpen` state, the __next__ execution of the function will result in a single attempt to execute the function. I think [Fowler's post](https://martinfowler.com/bliki/CircuitBreaker.html) makes this pretty clear, especially given the example code.

> Asked to call in the half-open state results in a trial call, which will either reset the breaker if successful or restart the timeout if not.

```ruby
class ResetCircuitBreaker...

  def call args
    case state
    when :closed, :half_open
      begin
        do_call args
      rescue Timeout::Error
        record_failure
        raise $!
      end
    when :open
      raise CircuitBreaker::Open
    else
      raise "Unreachable"
    end
  end
  def record_failure
    @failure_count += 1
    @last_failure_time = Time.now
    @monitor.alert(:open_circuit) if :open == state
  end
```

Thank you for pointing this out in the documentation, however.
