### ISSUE TITLE
Circuit breaker opened write after first fire if it fails.

### ISSUE THREAD

**Issue by fylhsq123** [bucharest-gold/opossum#217]
**Node.js Version:**
8.9.4
**Operating System:**
MacOS High Sierra 10.13.6 (Darwin Kernel Version 17.7.0)
**Steps to Produce Error:**
I'm getting circuit breaker opened write after first fire if it fails.
For example I creating circuit breaker with following options:
```javascript
const options = {
        timeout: 1000,
        errorThresholdPercentage: 50,
        rollingCountTimeout: 20000,
        resetTimeout: 30000
};
breaker = circuitBreaker(makeRequest, options);
```
And then if I'm getting failure on my first fire it calculates like 100% failures which is higher then 50% I set in options.
I believe this is happening because of this part of code in a module ('_./lib/circuit.js_'):
```javascript
const errorRate = stats.failures / stats.fires * 100;
if (errorRate > circuit.options.errorThresholdPercentage ||
    circuit.options.maxFailures >= stats.failures ||
    circuit.halfOpen) {
    circuit.open();
}
```
Maybe you should gather some statistic first without opening circuit but with handling fails. I mean like 10 fires or make additional parameter for that.

**Comment by lance** [comment]
I am aware of this issue, but I'm not sure this is a bug. The fact is that one execution of the function with one failure is 100% failure rate. But I will leave this open for now. It's possible that we can modify this conditional check to override if the amount of data is insufficient. But it's not clear to me the best and cleanest way to do this.

**Comment by fylhsq123** [comment]
I suppose it could be some additional parameter where user can set number of requests, before the circuit breaker will calculate the health of the service and decide if we need circuit to be opened.
What do you think about it?

**Comment by lance** [comment]
@fylhsq123 not exactly what you suggested, but you can test out my branch in the pull request to see what you think. Instead of a hard number, the circuit will ignore failures/timeouts for the purposes of open/close state until the `options.rollingCountTimeout` value has expired. Let me know how this works for you.
