### ISSUE TITLE
Add caching capability to circuits

### ISSUE THREAD

**Issue by lance** [bucharest-gold/opossum#23]
Our needs are not exactly the same as those of Hystrix, however that project does provide a good [reference point](https://github.com/Netflix/Hystrix/wiki/How-it-Works#RequestCaching).

A possible approach for this feature might look something like this.

* Caching is off by default. When a circuit is constructed, one of the options should be to turn caching on. Everything that follows assumes caching is enabled.
* Each circuit created is a key into a module-scoped `WeakMap`. The values are the returned results of the circuit breaker's action.
```js
const CACHE = new WeakMap();

class CircuitBreaker() {
  CACHE.set(this, undefined);
}
```
* When the circuit is fired, the map is checked first to determine if there is a cached value. If so, the cached value is immediately returned, before any checking of circuit state/fallback etc.
```js
function fire () {
  if (CACHE.get(this) !== undefined) return CACHE.get(this);
  // .... etc.
}
```
* Circuit statistics should include cache hits/misses.
* A user should be able to clear the cache for a circuit.
```js
class CircuitBreaker () {
  clearCache () {
    CACHE.set(this, undefined);
  }
}
```

This would only be useful for circuit breakers that access a fixed URL (e.g. no path parameters, or `POST`s), for which the data rarely changes. E.g. A user profile. 

**OPEN QUESTION:** Should the cache periodically reset itself? E.g. each circuit sets a timeout interval of 3 minutes, and invalidates its cache entry. If so, this timeout value should be user configurable. This would allow for situations where a user may have updated their profile from the previous example asynchronously. Instead of requiring the user to write code detecting a change, and then clearing the circuit's cache, since a change like this is not terribly important to update in real time, they can just wait for the cache entry to become invalidated after the timeout interval.

**Comment by helio-frota** [comment]
> Should the cache periodically reset itself?

IMO: maybe if it does not add a lot of complexity (code, usage and testing), it seems safer to auto invalidate rather than delegate to the user clearing the cache. But I still do not know if the gain makes much sense due circuit self timeout.

**Comment by lance** [comment]
Landed in https://github.com/bucharest-gold/opossum/commit/770950df181aa062800df34c9fe9180cac143f0e
