### ISSUE TITLE
Circuit Breaker Capacity

### ISSUE THREAD

**Issue by mobbyd1** [bucharest-gold/opossum#230]
Hello,

I would like to ask a question about using the number of concurrent requests on the circuit breaker. I noticed that the default limit, is 10 connections. Is there any reason for this number?

I ask because we have a requirement not to have a specific number of concurrent requests, so we would like to pass the highest possible value to the capacity (max int) in the circuit breaker instantiation. Can this lead to any problems?

Thanks

**Comment by lance** [comment]
Hi @mobbyd1 thanks for the question! You have found a flaw in my implementation. 👍 
At the moment, there is no way to have an infinite number of connections, although this would not be terribly difficult to change. But I expect that the upper limit of `Number.MAX_SAFE_INTEGER` is going to be greater than what any OS will allow.

```js
Number.MAX_SAFE_INTEGER
9007199254740991
```

If this is not sufficient for your needs, let me know and I will consider making a change.

**Comment by mobbyd1** [comment]
> Hi @mobbyd1 thanks for the question! You have found a flaw in my implementation. 👍
> At the moment, there is no way to have an infinite number of connections, although this would not be terribly difficult to change. But I expect that the upper limit of `Number.MAX_SAFE_INTEGER` is going to be greater than what any OS will allow.
> 
> ```js
> Number.MAX_SAFE_INTEGER
> 9007199254740991
> ```
> 
> If this is not sufficient for your needs, let me know and I will consider making a change.

Hi @lance, thank for the reply!

This number, MAX_SAFE_INTEGER, couldn't it be the default capacity?

**Comment by lance** [comment]
> This number, MAX_SAFE_INTEGER, couldn't it be the default capacity?

@mobbyd1 It could be, yes. I'll leave this issue open for now so that it can be considered. In the meantime, will this satisfy your needs?

**Comment by mobbyd1** [comment]
> > This number, MAX_SAFE_INTEGER, couldn't it be the default capacity?
> 
> @mobbyd1 It could be, yes. I'll leave this issue open for now so that it can be considered. In the meantime, will this satisfy your needs?

Hi @lance,

Yes, no problem.
Thanks!

**Comment by lance** [comment]
Fixed in https://github.com/bucharest-gold/opossum/pull/231
