### ISSUE TITLE
A circuit's status should have rolling percentages (optionally)

### ISSUE THREAD

**Issue by lance** [bucharest-gold/opossum#38]
The Hystrix data stream can use/display rolling percentile information about errors, fallbacks etc. We should provide this as an option.

See:
* https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream
* https://github.com/Netflix/Hystrix/wiki/Configuration#metrics.rollingPercentile.enabled

**Comment by lholmquist** [comment]
As part of this, we need to determine the time latency.  From what i understand, that is really the time at which the circuits fire event happens minus the time it takes for the success/error/... event to happen,  in milliseconds of course

**Comment by lance** [comment]
Yes, I think that makes sense.
