### ISSUE TITLE
A circuit's status data should be provided as a data stream

### ISSUE THREAD

**Issue by lance** [bucharest-gold/opossum#39]
Specifically, implement https://nodejs.org/api/stream.html#stream_class_stream_readable

**Comment by lholmquist** [comment]
on this now.  looking to https://github.com/awolden/brakes/blob/master/lib/globalStats.js for inspiration

**Comment by lholmquist** [comment]
added here  2d44df68f549b6b8149f49322f8b9cc7e32cc9c9
