### ISSUE TITLE
Circuit needs a Group property

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/opossum#43]
One of the properties in the Hystrix Data is "Group",  https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream

We can probably default this to be the same as the name property if nothing is passed in

**Comment by lance** [comment]
This can be closed, can't it?

**Comment by lholmquist** [comment]
Yup,  just looking for the commit.

closed via 3052f23af43c98a622bf51b25edcef969d9b39c0
