### ISSUE TITLE
Use semaphore isolation to limit concurrent requests

### ISSUE THREAD

**Issue by lance** [bucharest-gold/opossum#60]
## Fine Grained Bulkhead Pattern

The goal here is to implement a fine-grained bulkhead pattern similar to how Hystrix works in Java. This works hand-in-hand with circuit breakers to provide user-configurable client-side load balancing / throttling and helps to mitigate DoS attacks.

Before actually executing any of the circuit breaker wrapped code, the `fire()` function should acquire a semaphore, execute the function, and then release the semaphore. This prevents a client from unintentionally overloading a server with requests to a single resource, protecting against both programmer error (e.g. a loop that just spins, firing request after request), or malicious code designed to bring a service down.

### Things to Consider
* We need to find a reasonable default number of concurrent connections.
* We need to decide if we should check the semaphore first, or if we should check the open state first. If the circuit is open, we are essentially throttling anyway, so we don't need to acquire a semaphore, and we're not using any additional external resources because we are failing fast. 
* Does this limit also affect the fallback functions? If we decide that we check open state first, and potentially fallback, should the fallback functions be subject to the same rate limiting behavior.

**Comment by lance** [comment]
https://www.npmjs.com/package/semaphore

**Comment by helio-frota** [comment]
@lance I'm using https://www.npmjs.com/package/await-semaphore around the fire function.
Well, at least now I can run the tests and also this automatically runs the "leave".
But, I'm trying to understand to solve one issue with one of the tests (see on the screenshots ):

![a](https://user-images.githubusercontent.com/6443576/27046983-d4ff8eec-4f7c-11e7-9283-5791fb089d75.png)
![b](https://user-images.githubusercontent.com/6443576/27046984-d50057fa-4f7c-11e7-80a5-ecdbb978b104.png)

**Comment by helio-frota** [comment]
I'm going to try again with semaphore.. this other library has some weird behavior I dunno.
When I change the capacity nothing happens, 0, 1, 100...

**Comment by lance** [comment]
OK - if you are still having issues, send a link to your branch and I will
poke around.

**Comment by helio-frota** [comment]
@lance https://github.com/bucharest-gold/opossum/tree/opossum-60
