### ISSUE TITLE
Support infinite retries - maxFailures = 0?

### ISSUE THREAD

**Issue by jbcpollak** [bucharest-gold/opossum#74]
Hello,

We have some situations where we want to just keep retrying, and ideally it could be done programmatically inside opossum. Currently we have to write some wrapper code that checks if we want infinity, and retry ourselves manually.

**Comment by lance** [comment]
I'm curious what the scenario is where this would be useful. Why use a circuit breaker if you never want it to trip?

**Comment by jbcpollak** [comment]
Two reasons:

-you are using opossum for circuit breaking and you want to maintain the
convention (or wrapper utilities you've written around it) but want to
allow infinite retries in some cases.

There are some requests to a service you want to break, but other ones must
keep trying.

In our case we have a common rest model adapter that we use for all our
remote object calls, we circuit breaking for most calls, but certain ones
must keep retrying until it works. Without built in infinite retries the
code gets kind of clunky.

I realize our system should theoretically be designed so infinite retries
aren't necessary, but sometimes it isn't an option, and sometimes you are
retrofitting old code and can't clean everything up at once...

**Comment by lance** [comment]
Hmm, I can't say that I am convinced this is generally useful behavior to add to the project. The whole point of a circuit breaker is to trip at a given threshold. Making a change like this essentially eliminates that possibility. However, I think you may be able to achieve what you want by using `options.errorThresholdPercentage`. We currently do not check to see if that value is within the `0-100` range. We simply check if the error rate exceeds it [here](https://github.com/bucharest-gold/opossum/blob/master/lib/circuit.js#L435). By setting this option to some unreasonably large number, e.g. 1000, that will never be the result of our threshold calculation, the circuit should not be tripped.

I'm going to close this for now. If my suggestion above does not work for you, perhaps we can reconsider.

**Comment by jbcpollak** [comment]
@lance Hi, this is probably a naive question, but it just dawned on me - Opossum doesn't actually retry an operation, does it? 

If I understand Opossum correctly it performs the operation, which either succeeds, fails or times out. If its a failure or timeout, that gets recorded by opossum and opens the circuit (depending on configuration options), and the caller gets a rejected promise, no retries, right?

**Comment by lance** [comment]
@jbcpollak yes, that's right, no retries. Each call to `circuit.fire()` will invoke the supplied function at most one time. The code flow looks a little something like [this](http://lanceball.com/qcon-saopaulo-2017/#45). 

It's not a naive question - it just tells me my docs need to be better. :) I wrote a blog post about this stuff a few months ago. You might find it helpful. http://lanceball.com/words/2017/01/05/protect-your-node-js-rest-clients-with-circuit-breakers/

**Comment by jbcpollak** [comment]
thanks @lance - I'll check it out, thats a big help
